version: "3"

services:
  broker-services:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile
    restart: always
    ports:
      - 8080:8080
    deploy:
      mode: replicated
      replicas: 1

  auth-services:
    build:
      context: ./../authentication-service
      dockerfile: ./../authentication-service/authentication-service.dockerfile
    restart: always
    ports:
      - 8081:8080
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - DSN=host=postgres port=5432 user=postgres password=postgres dbname=users sslmode=disable timeZone=UTC connect_timeout=5

  postgres:
      image: postgres:latest
      restart: always
      ports:
        - 8002:5432
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: users 
      volumes:
        - ./db-data/postgres/:/var/lib/postgresql/data/
      deploy:
        mode: replicated
        replicas: 1
