version: "3"

services:
  broker-services:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile
    restart: always
    ports:
      - 8080:8080
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - auth-services
    networks:
      - email-network

  auth-services:
    build:
      context: ./../authentication-service
      dockerfile: ./../authentication-service/authentication-service.dockerfile
    restart: always
    ports:
      - 8081:8080
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - DSN=host=postgres port=5432 user=postgres password=postgres dbname=users sslmode=disable timeZone=UTC connect_timeout=5
    networks:
      - email-network

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 8002:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - email-network

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONDO_INITDB_DATABASE: email
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./db-data/mongo/:/data/db/

networks:
  email-network:
    driver: bridge
