version: "3"

services:
  broker-services:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile
    restart: always
    ports:
      - 8080:8080
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - auth-services
    networks:
      - email-network
  logger-services:
    depends_on:
      - mongo
    build:
      context: ./../logger-service
      dockerfile: ./../logger-service/logger-service.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1

    networks:
      - email-network

  auth-services:
    build:
      context: ./../authentication-service
      dockerfile: ./../authentication-service/authentication-service.dockerfile
    restart: always
    ports:
      - 8081:8080
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - DSN=host=postgres port=5432 user=postgres password=postgres dbname=users sslmode=disable timeZone=UTC connect_timeout=5
    networks:
      - email-network

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 8002:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - email-network

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONDO_INITDB_DATABASE: logs
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./db-data/mongo/:/data/db/
    networks:
      - email-network

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - email-network

  mailer-service:
    build:
      context: ./../mailer-service
      dockerfile: ./../mailer-service/mailer-service.dockerfile
    restart: always
    ports:
      - 8082:8080
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - mailhog
    environment:
      MAIL_DOMAIN: localhost
      MAIL_PORT: 1025
      MAIL_HOST: mailhog
      MAIL_ENCRYPTION: none
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      MAIL_FROM_NAME: "Mehul Kumar"
      MAIL_FROM_ADDRESS: "mehulKumar@dev.com"
    networks:
      - email-network
  
  rabitmq:
    image: rabbitmq:latest
    ports:
      - 5672:5672
    networks:
      - email-network
    volumes:
      - ./db-data/rabbitmq/:/var/lib/rabbitmq/

networks:
  email-network:
    driver: bridge
